# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SegmentSelectorUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 629)
        self.base = QtWidgets.QWidget(MainWindow)
        self.base.setObjectName("base")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.base)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dataBx = QtWidgets.QWidget(self.base)
        self.dataBx.setObjectName("dataBx")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dataBx)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.collectionPrevBtn = QtWidgets.QPushButton(self.dataBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectionPrevBtn.sizePolicy().hasHeightForWidth())
        self.collectionPrevBtn.setSizePolicy(sizePolicy)
        self.collectionPrevBtn.setObjectName("collectionPrevBtn")
        self.horizontalLayout_2.addWidget(self.collectionPrevBtn)
        self.collectionCmb = QtWidgets.QComboBox(self.dataBx)
        self.collectionCmb.setObjectName("collectionCmb")
        self.horizontalLayout_2.addWidget(self.collectionCmb)
        self.collectionNextBtn = QtWidgets.QPushButton(self.dataBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectionNextBtn.sizePolicy().hasHeightForWidth())
        self.collectionNextBtn.setSizePolicy(sizePolicy)
        self.collectionNextBtn.setObjectName("collectionNextBtn")
        self.horizontalLayout_2.addWidget(self.collectionNextBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.figureBx = QtWidgets.QVBoxLayout()
        self.figureBx.setObjectName("figureBx")
        self.verticalLayout.addLayout(self.figureBx)
        self.horizontalLayout.addWidget(self.dataBx)
        self.tabWidget = QtWidgets.QTabWidget(self.base)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(210, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.segmentsTb = QtWidgets.QWidget()
        self.segmentsTb.setObjectName("segmentsTb")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.segmentsTb)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.clearSegmentBtn = QtWidgets.QPushButton(self.segmentsTb)
        self.clearSegmentBtn.setObjectName("clearSegmentBtn")
        self.verticalLayout_5.addWidget(self.clearSegmentBtn)
        self.segmentIdTxt = QtWidgets.QLineEdit(self.segmentsTb)
        self.segmentIdTxt.setObjectName("segmentIdTxt")
        self.verticalLayout_5.addWidget(self.segmentIdTxt)
        self.saveSegmentBtn = QtWidgets.QPushButton(self.segmentsTb)
        self.saveSegmentBtn.setObjectName("saveSegmentBtn")
        self.verticalLayout_5.addWidget(self.saveSegmentBtn)
        self.specialSegmentsGrp = QtWidgets.QGroupBox(self.segmentsTb)
        self.specialSegmentsGrp.setFlat(False)
        self.specialSegmentsGrp.setObjectName("specialSegmentsGrp")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.specialSegmentsGrp)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.saveBslFlatBtn = QtWidgets.QPushButton(self.specialSegmentsGrp)
        self.saveBslFlatBtn.setObjectName("saveBslFlatBtn")
        self.gridLayout.addWidget(self.saveBslFlatBtn, 0, 1, 1, 1)
        self.saveBslBeadsBtn = QtWidgets.QPushButton(self.specialSegmentsGrp)
        self.saveBslBeadsBtn.setObjectName("saveBslBeadsBtn")
        self.gridLayout.addWidget(self.saveBslBeadsBtn, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.specialSegmentsGrp)
        self.removeSegmentBtn = QtWidgets.QPushButton(self.segmentsTb)
        self.removeSegmentBtn.setEnabled(False)
        self.removeSegmentBtn.setObjectName("removeSegmentBtn")
        self.verticalLayout_5.addWidget(self.removeSegmentBtn)
        self.label = QtWidgets.QLabel(self.segmentsTb)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.segmentLst = QtWidgets.QListWidget(self.segmentsTb)
        self.segmentLst.setObjectName("segmentLst")
        self.verticalLayout_5.addWidget(self.segmentLst)
        self.exportSegmentBtn = QtWidgets.QPushButton(self.segmentsTb)
        self.exportSegmentBtn.setObjectName("exportSegmentBtn")
        self.verticalLayout_5.addWidget(self.exportSegmentBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.loadDirectoryBtn = QtWidgets.QPushButton(self.segmentsTb)
        self.loadDirectoryBtn.setObjectName("loadDirectoryBtn")
        self.verticalLayout_5.addWidget(self.loadDirectoryBtn)
        self.quitBtn = QtWidgets.QPushButton(self.segmentsTb)
        self.quitBtn.setObjectName("quitBtn")
        self.verticalLayout_5.addWidget(self.quitBtn)
        self.tabWidget.addTab(self.segmentsTb, "")
        self.settingsTb = QtWidgets.QWidget()
        self.settingsTb.setObjectName("settingsTb")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settingsTb)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plotOptionsGrp = QtWidgets.QGroupBox(self.settingsTb)
        self.plotOptionsGrp.setObjectName("plotOptionsGrp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.plotOptionsGrp)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.plotOptionsGrp)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.timeYAxisCmb = QtWidgets.QComboBox(self.plotOptionsGrp)
        self.timeYAxisCmb.setObjectName("timeYAxisCmb")
        self.verticalLayout_3.addWidget(self.timeYAxisCmb)
        self.label_2 = QtWidgets.QLabel(self.plotOptionsGrp)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.distXAxisCmb = QtWidgets.QComboBox(self.plotOptionsGrp)
        self.distXAxisCmb.setObjectName("distXAxisCmb")
        self.verticalLayout_3.addWidget(self.distXAxisCmb)
        self.label_3 = QtWidgets.QLabel(self.plotOptionsGrp)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.distYAxisCmb = QtWidgets.QComboBox(self.plotOptionsGrp)
        self.distYAxisCmb.setObjectName("distYAxisCmb")
        self.verticalLayout_3.addWidget(self.distYAxisCmb)
        self.verticalLayout_2.addWidget(self.plotOptionsGrp)
        self.groupBox_2 = QtWidgets.QGroupBox(self.settingsTb)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupExportBeadCbx = QtWidgets.QCheckBox(self.groupBox_2)
        self.groupExportBeadCbx.setObjectName("groupExportBeadCbx")
        self.verticalLayout_4.addWidget(self.groupExportBeadCbx)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.sourceTypeCmb = QtWidgets.QComboBox(self.groupBox_2)
        self.sourceTypeCmb.setObjectName("sourceTypeCmb")
        self.verticalLayout_4.addWidget(self.sourceTypeCmb)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.settingsTb, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.base)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.collectionPrevBtn.setText(_translate("MainWindow", "<"))
        self.collectionNextBtn.setText(_translate("MainWindow", ">"))
        self.clearSegmentBtn.setText(_translate("MainWindow", "Clear Segments"))
        self.segmentIdTxt.setPlaceholderText(_translate("MainWindow", "Segment ID (optional)"))
        self.saveSegmentBtn.setText(_translate("MainWindow", "Save Segment"))
        self.specialSegmentsGrp.setTitle(_translate("MainWindow", "Add as special sgement"))
        self.saveBslFlatBtn.setText(_translate("MainWindow", "bslFlat"))
        self.saveBslBeadsBtn.setText(_translate("MainWindow", "bslBeads"))
        self.removeSegmentBtn.setText(_translate("MainWindow", "Remove Segment"))
        self.label.setText(_translate("MainWindow", "Segments:"))
        self.exportSegmentBtn.setText(_translate("MainWindow", "Export Segments"))
        self.loadDirectoryBtn.setText(_translate("MainWindow", "Load Directory"))
        self.quitBtn.setText(_translate("MainWindow", "Quit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.segmentsTb), _translate("MainWindow", "Segments"))
        self.plotOptionsGrp.setTitle(_translate("MainWindow", "Plots"))
        self.label_5.setText(_translate("MainWindow", "Time Plot Y-Axis:"))
        self.label_2.setText(_translate("MainWindow", "Distance Plot X-Axis:"))
        self.label_3.setText(_translate("MainWindow", "Distance Plot Y-Axis:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Data"))
        self.groupExportBeadCbx.setToolTip(_translate("MainWindow", "<html><head/><body><p><nobr>If set, creates only one Tweezers Analysis file per Bead ID</nobr> and stores all segments in this single file. Otherwise, one file is created per trial file.</p></body></html>"))
        self.groupExportBeadCbx.setText(_translate("MainWindow", "Group Export by Bead"))
        self.label_4.setText(_translate("MainWindow", "Data Source:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTb), _translate("MainWindow", "Settings"))

