__doc__="""\
Collection of models put forward in the literature to explain the motion
RNA Polymerases.

the aim is to fit these models to data obtained by optical tweezer experiments.

References:

:cite:`Ishibashi:2014cd1987:nelson`

.. bibliography:: tweezer.bib

"""


class TranscriptionModel(object):
    """
    General container class for transcription models
    """
    def __init__(self):
        self.name = "Transcription Model"


class BacktrackingModel(TranscriptionModel):
    """
    This model assumes that backtracking is the only mechanism for pausing.

    It models backtracking as a diffusive process with an absorbing barrier.
    """
    pass


class PowerLawModel(TranscriptionModel):
    """
    This model is a generic description of the observed pause distributions,
    but does not provide a clear insight of how these distributions come about.
    """
    pass


class MultipleExponentialModel(TranscriptionModel):
    """
    This model corresponds to distributions generated by
    conventional biochemical kinetic models, i.e. discrete states
    connected by reaction rates.
    """
    pass