#!/usr/bin/env python
#-*- coding: utf-8 -*-

from collections import namedtuple


class TweebotDictionary(namedtuple('TweebotDictionary', ['date',
                                   'timeOfExperiment',
                                   'laserDiodeTemp',
                                   'laserDiodeHours',
                                   'laserDiodeCurrent',
                                   'andorAodCenterX',
                                   'andorAodCenterY',
                                   'andorAodRangeX',
                                   'andorAodRangeY',
                                   'ccdAodCenterX',
                                   'ccdAodCenterY',
                                   'ccdAodRangeX',
                                   'ccdAodRangeY',
                                   'andorPmCenterX',
                                   'andorPmCenterY',
                                   'andorPmRangeX',
                                   'andorPmRangeY',
                                   'ccdPmCenterX',
                                   'ccdPmCenterY',
                                   'ccdPmRangeX',
                                   'ccdPmRangeY',
                                   'andorPixelSizeX',
                                   'andorPixelSizeY',
                                   'ccdPixelSizeX',
                                   'ccdPixelSizeY',
                                   'aodDetectorOffsetX',
                                   'aodDetectorOffsetY',
                                   'aodStiffnessX',
                                   'aodStiffnessY',
                                   'aodDistanceConversionX',
                                   'aodDistanceConversionY',
                                   'pmDetectorOffsetX',
                                   'pmDetectorOffsetY',
                                   'pmStiffnessX',
                                   'pmStiffnessY',
                                   'pmDistanceConversionX',
                                   'pmDistanceConversionY',
                                   'aodBeadRadius',
                                   'pmBeadRadius',
                                   'samplingRate',
                                   'nSamples',
                                   'deltaTime',
                                   'timeStep'])):
    """
    TweebotDictionary is build on a namedtuple for easy access of variables \
    with the dot notation. In addition to the namedtuple it allows for default\
    values to be set and extra values to be added when needed. However, it \
    preserves the immutability of the namedtuple on first glance. To set a \
    value after initiation use

    d = d._replace(key=value)

    """
    def __new__(cls, date=None,
                timeOfExperiment=None,
                laserDiodeTemp=None,
                laserDiodeHours=None,
                laserDiodeCurrent=None,
                andorAodCenterX=None,
                andorAodCenterY=None,
                andorAodRangeX=None,
                andorAodRangeY=None,
                ccdAodCenterX=None,
                ccdAodCenterY=None,
                ccdAodRangeX=None,
                ccdAodRangeY=None,
                andorPmCenterX=None,
                andorPmCenterY=None,
                andorPmRangeX=None,
                andorPmRangeY=None,
                ccdPmCenterX=None,
                ccdPmCenterY=None,
                ccdPmRangeX=None,
                ccdPmRangeY=None,
                andorPixelSizeX=None,
                andorPixelSizeY=None,
                ccdPixelSizeX=None,
                ccdPixelSizeY=None,
                aodDetectorOffsetX=None,
                aodDetectorOffsetY=None,
                aodStiffnessX=None,
                aodStiffnessY=None,
                aodDistanceConversionX=None,
                aodDistanceConversionY=None,
                pmDetectorOffsetX=None,
                pmDetectorOffsetY=None,
                pmStiffnessX=None,
                pmStiffnessY=None,
                pmDistanceConversionX=None,
                pmDistanceConversionY=None,
                aodBeadRadius=None,
                pmBeadRadius=None,
                samplingRate=None,
                nSamples=None,
                deltaTime=None,
                timeStep=None):
        # add default values
        return super(TweebotDictionary, cls).__new__(cls, date,
                                                     timeOfExperiment,
                                                     laserDiodeTemp,
                                                     laserDiodeHours,
                                                     laserDiodeCurrent,
                                                     andorAodCenterX,
                                                     andorAodCenterY,
                                                     andorAodRangeX,
                                                     andorAodRangeY,
                                                     ccdAodCenterX,
                                                     ccdAodCenterY,
                                                     ccdAodRangeX,
                                                     ccdAodRangeY,
                                                     andorPmCenterX,
                                                     andorPmCenterY,
                                                     andorPmRangeX,
                                                     andorPmRangeY,
                                                     ccdPmCenterX,
                                                     ccdPmCenterY,
                                                     ccdPmRangeX,
                                                     ccdPmRangeY,
                                                     andorPixelSizeX,
                                                     andorPixelSizeY,
                                                     ccdPixelSizeX,
                                                     ccdPixelSizeY,
                                                     aodDetectorOffsetX,
                                                     aodDetectorOffsetY,
                                                     aodStiffnessX,
                                                     aodStiffnessY,
                                                     aodDistanceConversionX,
                                                     aodDistanceConversionY,
                                                     pmDetectorOffsetX,
                                                     pmDetectorOffsetY,
                                                     pmStiffnessX,
                                                     pmStiffnessY,
                                                     pmDistanceConversionX,
                                                     pmDistanceConversionY,
                                                     aodBeadRadius,
                                                     pmBeadRadius,
                                                     samplingRate,
                                                     nSamples,
                                                     deltaTime,
                                                     timeStep)


class TweezerUnits(TweebotDictionary):
        def __new__(cls, date=None,
                    timeOfExperiment=None,
                    laserDiodeTemp='C',
                    laserDiodeHours='h',
                    laserDiodeCurrent='A',
                    andorAodCenterX='px',
                    andorAodCenterY='px',
                    andorAodRangeX='px',
                    andorAodRangeY='px',
                    ccdAodCenterX='px',
                    ccdAodCenterY='px',
                    ccdAodRangeX='px',
                    ccdAodRangeY='px',
                    andorPmCenterX='px',
                    andorPmCenterY='px',
                    andorPmRangeX='px',
                    andorPmRangeY='px',
                    ccdPmCenterX='px',
                    ccdPmCenterY='px',
                    ccdPmRangeX='px',
                    ccdPmRangeY='px',
                    andorPixelSizeX='nm',
                    andorPixelSizeY='nm',
                    ccdPixelSizeX='nm',
                    ccdPixelSizeY='nm',
                    aodDetectorOffsetX='V',
                    aodDetectorOffsetY='V',
                    aodStiffnessX='pN/nm',
                    aodStiffnessY='pN/nm',
                    aodDistanceConversionX='V/nm',
                    aodDistanceConversionY='V/nm',
                    pmDetectorOffsetX='V',
                    pmDetectorOffsetY='V',
                    pmStiffnessX='pN/nm',
                    pmStiffnessY='pN/nm',
                    pmDistanceConversionX='V/nm',
                    pmDistanceConversionY='V/nm',
                    aodBeadRadius='nm',
                    pmBeadRadius='nm',
                    samplingRate='Hz',
                    nSamples='int',
                    deltaTime='s',
                    timeStep='s'):
            # add default values
            return super(TweezerUnits, cls).__new__(cls, date,
                                                    timeOfExperiment,
                                                    laserDiodeTemp,
                                                    laserDiodeHours,
                                                    laserDiodeCurrent,
                                                    andorAodCenterX,
                                                    andorAodCenterY,
                                                    andorAodRangeX,
                                                    andorAodRangeY,
                                                    ccdAodCenterX,
                                                    ccdAodCenterY,
                                                    ccdAodRangeX,
                                                    ccdAodRangeY,
                                                    andorPmCenterX,
                                                    andorPmCenterY,
                                                    andorPmRangeX,
                                                    andorPmRangeY,
                                                    ccdPmCenterX,
                                                    ccdPmCenterY,
                                                    ccdPmRangeX,
                                                    ccdPmRangeY,
                                                    andorPixelSizeX,
                                                    andorPixelSizeY,
                                                    ccdPixelSizeX,
                                                    ccdPixelSizeY,
                                                    aodDetectorOffsetX,
                                                    aodDetectorOffsetY,
                                                    aodStiffnessX,
                                                    aodStiffnessY,
                                                    aodDistanceConversionX,
                                                    aodDistanceConversionY,
                                                    pmDetectorOffsetX,
                                                    pmDetectorOffsetY,
                                                    pmStiffnessX,
                                                    pmStiffnessY,
                                                    pmDistanceConversionX,
                                                    pmDistanceConversionY,
                                                    aodBeadRadius,
                                                    pmBeadRadius,
                                                    samplingRate,
                                                    nSamples,
                                                    deltaTime,
                                                    timeStep)
